import com.lightbend.lagom.core.LagomVersion

organization in ThisBuild := "org.anized"
version in ThisBuild := "1.0-SNAPSHOT"
scalaVersion in ThisBuild := "2.12.10"

val postgresDriver = "org.postgresql" % "postgresql" % "42.2.5"
val macwire = "com.softwaremill.macwire" %% "macros" % "2.3.2" % "provided"
val scalaTest = "org.scalatest" %% "scalatest" % "3.0.7" % Test
val akkaDiscoveryKubernetesApi = "com.lightbend.akka.discovery" %% "akka-discovery-kubernetes-api" % "1.0.0"
val lagomScaladslAkkaDiscovery = "com.lightbend.lagom" %% "lagom-scaladsl-akka-discovery-service-locator" % LagomVersion.current

val repoUser = "sothach"
val repo = "dscr.io"
javaOptions in Universal ++= Seq(
  "-Dpidfile.path=/dev/null"
)
def dockerSettings = Seq(
  maintainer in Docker := "phillips.roy@gmail.com",
  dockerUsername := Some(repoUser),
  dockerUpdateLatest := true,
  dockerExposedPorts ++= Seq(9000),
  dockerExposedVolumes := Seq("/opt/docker/logs")
)

// Update the version generated by sbt-dynver to remove any + characters, since these are illegal in docker tags
version in ThisBuild ~= (_.replace('+', '-'))
dynver in ThisBuild ~= (_.replace('+', '-'))

lazy val `viewer` = (project in file("."))
  .aggregate(`viewer-api`, `viewer-app`)

lazy val `viewer-api` = (project in file("viewer-api"))
  .settings(libraryDependencies ++= Seq(lagomScaladslApi))
  .settings(publish in Docker := {}, publishArtifact := false)

lazy val `viewer-app` = (project in file("viewer-app"))
  .enablePlugins(LagomScala)
  .enablePlugins(DockerPlugin)
  .settings(
    libraryDependencies ++= Seq(
      lagomScaladslPersistenceJdbc,
      lagomScaladslKafkaBroker,
      lagomScaladslTestKit,
      macwire,
      scalaTest,
      postgresDriver,
      lagomScaladslAkkaDiscovery,
      akkaDiscoveryKubernetesApi
    ),
    Seq(
      aggregate in Docker := false,
      dockerRepository := Some(s"$repo/$repoUser/viewer"),
      dockerAlias := DockerAlias(Some(repo), Some(repoUser), "viewer", Some("latest")),
    ),
    dockerSettings
  )
  .settings(lagomForkedTestSettings)
  .dependsOn(`viewer-api`)

lagomCassandraEnabled in ThisBuild := false