version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: shopping_cart_postgres
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

  app:
    image: viewer-app
    links:
      - postgres
    entrypoint: “java -Djava.security.egd=file:/dev/./urandom -jar /opt/app.jar”
