apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: viewer-app
  namespace: lumina
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viewer-app

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: viewer-app
    spec:
      restartPolicy: Always
      containers:
        - name: viewer-app
          image: "viewer-app:1.0-SNAPSHOT"
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
            - name: APPLICATION_SECRET
              value: QCYtAnfkaZiwrNwnxIlR6CTfG3gf90Latabg5241ABR5W1uDFNIkn
            - name: POSTGRESQL_URL
              value: "jdbc:postgresql://postgresql/lumina"
            - name: POSTGRESQL_USERNAME
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: KAFKA_SERVICE_NAME
              value: "kafka"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "3"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: viewer-app
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: viewer-app
  type: LoadBalancer